title: The Ngoding
description: > # this means to ignore newlines until "baseurl:"
  Sekedar ingin berbagi, dan bukan yang paling mampu, semoga dapat bermanfaat buat rekan-rekan pembaca sekalian.
permalink: '/:year/:month/:day/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thengoding.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: The Ngoding # add your name
author-img: code.png # add your photo
about-author: Sekedar ingin berbagi, dan bukan yang paling mampu, semoga dapat bermanfaat buat rekan-rekan pembaca sekalian.
social-twitter: # add your Twitter handle
social-facebook: congfandii
social-github: congfandi 
social-linkedin: moh-supandi-49b717119/
social-email: congfandi@gmail.com
# Disqus
discus-identifier: congfandi

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-archives

paginate: 8
paginate_path: "/page/:num"

jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
